os: osx
osx_image: xcode9
language: ruby
rvm:
  - ruby
services:
  - mysql
before_install:
  - brew install mysql
  - gem install bundler
before_script:
  - cd spec/test_app
  - bundle install
  - rails db:setup
  - cd ../../
script: bundle exec rake spec