os: osx
osx_image: xcode9
language: ruby
rvm:
  - ruby
before_install:
  - locale
  - brew install mysql
  - brew services start mysql
  - brew install phantomjs
  - gem install bundler
before_script:
  - cd spec/test_app
  - bundle update --jobs=3 --retry=3
  - rails db:setup
  - cd ../../
  - bundle update --jobs=3 --retry=3
script: bundle exec rake spec